apiVersion: v1
kind: Service
metadata:
  name: ea-project-demo-service
spec:
  selector:
    app: ea-demo-project
  type: NodePort
  ports:
    - name: ea-project-demo-port
      protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30000
