spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ea_lab13
    username: yogen
    password: dat1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

# Logging configuration
logging:
  level:
    root: INFO
    org:
      springframework: ERROR

management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always