package com.eaproject.common;

public enum ProductTitle {
    SMARTPHONE,
    LAPTOP,
    HEADPHONES,
    TELEVISION,
    REFRIGERATOR,
    MICROWAVE_OVEN,
    WASHING_MACHINE,
    AIR_CONDITIONER,
    DIGITAL_CAMERA,
    SMARTWATCH,
    VACUUM_CLEANER,
    BLENDER,
    COFFEE_MAKER,
    ELECTRIC_KETTLE,
    HAIR_DRYER,
    TREADMILL,
    YOGA_MAT,
    DUMBBELLS,
    BICYCLE,
    RUNNING_SHOES;
}