apiVersion: v1
kind: Service
metadata:
  name: ea-project-demo-loadbalancer
spec:
  selector:
    app: ea-demo-project
  type: LoadBalancer
  ports:
    - name: ea-project-demo-port
      protocol: TCP
      port: 2200
      targetPort: 8080
