apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ea-demo-project-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ea-demo-project
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50