apiVersion: v1
kind: Service
metadata:
  name: ea-project-demo-nodeport
spec:
  type: NodePort
  selector:
    app: ea-demo-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
