apiVersion: apps/v1
kind: Deployment
metadata:
    name: ea-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ea-demo-project
  template:
    metadata:
      labels:
        app: ea-demo-project
    spec:
      containers:
        - name: ea-demo-project
          image: ngaurav07/k8s-spring-demo:v1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "300Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 10